title: Dev Logs - Experiments in Code, Communication & Strategy
description: A running log of projects and ideas—covering growth engineering, open source, SaaS, developer relations, and the tools that keep things moving (or break them entirely).
seo_title: Dev Logs - Experiments in Code, Communication & Strategy
seo_description: A running log of projects and ideas—covering growth engineering, open source, SaaS, developer relations, and the tools that keep things moving (or break them entirely).
baseurl: "" # Leave empty if publishing from the root of the repository
url: "https://dvoorhees.com" # Replace with your custom domain

defaults:
  - scope:
      type: posts
    values:
      lyket_button: true

collections:
  projects:
    output: true
    permalink: /projects/:name/

  pages:
    output: true
    permalink: /:name/

permalink: /:year/:month/:day/:title/
